# Generated by Django 6.0.4 on 2026-04-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
