# Generated by Django 6.0.4 on 2026-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_document_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='building_number',
            new_name='license_number',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='registration_number',
            new_name='tax_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='local_place',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.RemoveField(
            model_name='company',
            name='street_name',
        ),
        migrations.AddField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
