# Generated by Django 6.0.4 on 2026-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_customfield_customfieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldvalue',
            name='file_value',
            field=models.FileField(blank=True, null=True, upload_to='custom_uploads/'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('date', 'Date Picker'), ('number', 'Number Only'), ('file', 'File / Image Upload')], default='text', max_length=20),
        ),
    ]
