# Generated by Django 6.0.4 on 2026-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_customfieldvalue_file_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='show_on_card',
            field=models.BooleanField(default=False),
        ),
    ]
