# Generated by Django 6.0.4 on 2026-04-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_customfield_show_on_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_logout_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
