# Generated by Django 6.0.4 on 2026-04-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_historylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='expire_alert_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='company',
            name='recent_update_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
