# Generated by Django 6.0.4 on 2026-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_company_expire_alert_days_company_recent_update_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='alert_on_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='alert_on_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='alert_on_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='alert_on_upload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='staff_permission_level',
            field=models.CharField(default='full', max_length=20),
        ),
    ]
