# Generated by Django 6.0.4 on 2026-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_company_alert_on_delete_company_alert_on_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_domain',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
